version: '3.4'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:6.0.2
    ports:
      - 9001:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
          define('JWT_AUTH_SECRET_KEY', 'z9?>-)zlg+fzYhbxfWJrs960|.xIMB@G<g>c+:vSlfgpcJX|x3#~P3q][%[,TCZp');
          define('JWT_AUTH_CORS_ENABLE', true);
    volumes:
      - ./volumes/jwt-auth:/var/www/html/wp-content/plugins/jwt-auth
      - ./tmp:/tmp/local
      - wordpress:/var/www/html

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    entrypoint: wp --allow-root
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
          define('JWT_AUTH_SECRET_KEY', 'z9?>-)zlg+fzYhbxfWJrs960|.xIMB@G<g>c+:vSlfgpcJX|x3#~P3q][%[,TCZp');
          define('JWT_AUTH_CORS_ENABLE', true);
    volumes:
      - ./volumes/jwt-auth:/var/www/html/wp-content/plugins/jwt-auth
      - ./tmp:/tmp/local
      - wordpress:/var/www/html
    # workaround for when we need file permissions, NB. need to use the --allow-root flag with this
    user: "${UID}:${GID}"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9002:80
    environment:
      MYSQL_ROOT_PASSWORD: password

  composer:
    image: jwt-auth/composer:7.4
    # entrypoint: '/app/wpcs/vendor/bin/phpcs'
    ports:
      - 80:80
    volumes:
      - ./volumes/jwt-auth:/app

volumes:
  wordpress: